on: [pull_request]
name: Running tests
jobs:
  test:
    name: Rinning tests with pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
        architecture: x64
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: pytest