on: [pull_request]
name: Running tests
jobs:
  test:
    name: Rinning tests with pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        python -m pip install numpy
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: pytest